import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Footer, Header } from "@/custom-ui";
import "../styles/global.css";
import "../styles/utils.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Monte's Golf",
    default: "Welcome",
  },
  description: "Generated by Che",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Header />
          <main className="wrapper">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
