import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Footer, Header } from "@/custom-ui";
import "../styles/global.css";
import "../styles/utils.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Monte's Golf",
    default: "Welcome",
  },
  description: "Generated by Che",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Gelasio:ital,wght@0,400..700;1,400..700&display=swap"
          rel="stylesheet"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Calistoga&family=Gelasio:ital,wght@0,400..700;1,400..700&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <Provider>
          <Header />
          <main className="wrapper">{children}</main>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
